name: PHP Composer

on:
  push:
    branches: ["staging"]


permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: confirm environment
        run: composer check-platform-reqs

      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-all

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Create destination directory for compiled CSS
        run: mkdir -vp $GITHUB_WORKSPACE/css


      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.6.0
        with:
          source: scss/style.scss
          destination: css/style.css

      - name: Add and Commit changes to compiled-css branch
        run: |
          git add css/*
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          directory: css
          commit_message: "Update compiled CSS files"
